GRN_NAVY = GRN_NAVY or {}
GRN_NAVY.Lang = GRN_NAVY.Lang or {}

local L = GRN_NAVY.Lang

GRN_NAVY.Config = GRN_NAVY.Config or {}
GRN_NAVY.Config.Language = GRN_NAVY.Config.Language or "en"

-- ─────────────────────────────────────────────
--  Translation Tables
-- ─────────────────────────────────────────────
L.Strings = {

    -- ── English (base) ───────────────────────
    en = {
        -- Server log messages
        log_mysql_connected      = "MySQL connection established",
        log_mysql_table_error    = "Error creating MySQL table: ",
        log_mysql_fail           = "MySQL connection failed: ",
        log_mysql_load_error     = "Error loading MySQL whitelist: ",
        log_mysql_save_row_error = "Error saving MySQL row: ",
        log_mysql_clear_error    = "Error clearing MySQL whitelist: ",
        log_mysqloo_missing      = "mysqloo is not installed, using native storage",

        -- Spawn errors
        err_entity_not_found     = "Entity does not exist: ",
        err_cannot_create_ent    = "Could not create entity ",
        err_hyperspace_missing   = "The vanilla_hyperspace_ship entity does not exist",
        err_hyperspace_anim_fail = "Could not create hyperspace animation",
        err_capital_invalid      = "Invalid capital ship",
        err_capital_limit        = "Limit reached for that ship",
        err_capital_noent        = "Entity does not exist: ",
        err_capital_spawn_fail   = "Error creating capital ship: ",
        err_fighter_invalid      = "Invalid fighter",
        err_fighter_limit        = "Limit reached for that fighter",
        err_fighter_noent        = "Entity does not exist: ",
        err_fighter_no_capital   = "You must select a capital ship from your team",
        err_fighter_spawn_fail   = "Could not create fighter",
        err_supply_invalid       = "Invalid supply",
        err_supply_limit         = "Limit reached for that supply",
        err_supply_noent         = "Entity does not exist: ",
        err_supply_no_capital    = "You must select a capital ship from your team",
        err_supply_no_target     = "You must mark a delivery point",
        err_supply_transport_missing = "Transport entity does not exist: ",
        err_supply_transport_fail    = "Could not create supply transport",
        err_supply_spawn_fail    = "Could not create supply",
        err_pod_invalid          = "Invalid escape pod",
        err_pod_limit            = "Limit reached for that escape pod",
        err_pod_noent            = "Entity does not exist: ",
        err_pod_no_capital       = "You must select a capital ship from your team",
        err_pod_no_target        = "You must mark a drop point",
        err_pod_no_players       = "Select at least one player for the escape pod",
        err_pod_spawn_fail       = "Could not create escape pod",
        err_ship_invalid         = "Invalid ship",
        err_ship_not_registered  = "Ship is not registered",
        err_turbolaser_missing   = "The heart_turbolaser_spawner entity does not exist",
        err_bombard_generic      = "Could not start bombardment",

        -- Chat messages (server → player)
        chat_job_disabled        = "[GRN Navy] Your job is not enabled to use /navy",
        chat_no_whitelist_access = "[GRN Navy] You do not have access to the whitelist",
        chat_whitelist_saved     = "[GRN Navy] Whitelist updated",
        chat_capital_jumping     = "[GRN Navy] Capital ship entering via hyperspace",
        chat_fighter_deployed    = "[GRN Navy] Fighter deployed. Players assigned: ",
        chat_supply_deployed     = "[GRN Navy] Supply deployed",
        chat_pod_deployed        = "[GRN Navy] Escape pod deployed. Players assigned: ",
        chat_ship_withdrawn_fx   = "[GRN Navy] Ship withdrawn via hyperspace",
        chat_ship_withdrawn_nofx = "[GRN Navy] Ship withdrawn (no animation): ",
        chat_bombard_started     = "[GRN Navy] Turbolaser bombardment started",
        chat_bombard_too_far     = "[GRN Navy] The ship is too far to bombard that area",
        chat_bombard_error       = "[GRN Navy] ",
        chat_welcome             = "[GRN Navy] Use /navy if your job was enabled and /whitelistnavy if you are authorized staff",

        -- HUD / RTS overlay
        hud_controls             = "WASD move camera | Q/E rotate | Left click select | scroll zoom | exit mode: ",
        hud_marking_supply       = " | MARKING SUPPLY",
        hud_marking_pod          = " | MARKING ESCAPE POD",
        hud_bombard_mode         = " | BOMBARDMENT MODE",
        hud_move_mode            = " | MOVE MODE",
        hud_crosshair_target     = "Target",
        hud_mode_supply          = "MARK SUPPLY",
        hud_mode_pod             = "MARK ESCAPE POD",
        hud_mode_bombard         = "BOMBARDMENT MODE",
        hud_mode_move            = "MOVE MODE",
        hud_exit_hint            = " | press  to exit",

        -- HTML menu labels
        menu_title               = "GRN Navy System",
        menu_loading             = "Loading...",
        menu_team_prefix         = "Team: ",
        menu_no_team             = "No Team",
        menu_available_players   = "Available Players",
        menu_capital_ships       = "Capital Ships",
        menu_btn_deploy_capital  = "Deploy Capital",
        menu_btn_withdraw        = "Withdraw Selected",
        menu_fighters            = "Fighters",
        menu_fighters_hint       = "Select players from the list and then deploy the fighter.",
        menu_btn_deploy_fighter  = "Deploy Fighter",
        menu_supplies            = "Supplies",
        menu_supplies_hint       = "Select the capital and then mark the point where the supply ship should arrive.",
        menu_btn_request_supply  = "Request Supply & Mark Point",
        menu_escape_pods         = "Escape Pods",
        menu_pods_hint           = "Configurable LVS Pod. Select up to 5 players and then mark the drop point.",
        menu_btn_launch_pod      = "Launch Escape Pod",
        menu_combat_control      = "Combat Control",
        menu_btn_bombard         = "Bombardment Mode",
        menu_btn_move            = "Move Ship",
        menu_btn_refresh         = "Refresh",
        menu_btn_exit_mode       = "Exit Active Mode",
        menu_combat_hint         = "Select a ship, tap Move or Bombardment and the menu will hide. The key configured in config.lua also exits the mode.",
        menu_active_ships        = "Active Ships",
        menu_ship_hp             = "HP",
        menu_ship_shield         = "Shield",
        menu_btn_close           = "Close / Exit RTS",

        -- Whitelist panel (native GMod UI)
        wl_title                 = "GRN Navy  ·  Whitelist",
        wl_col_job               = "Job / Command",
        wl_col_team              = "Team",
        wl_col_enabled           = "Enabled",
        wl_team_republic         = "Republic",
        wl_team_cis              = "Separatists",
        wl_btn_save              = "Save",

        -- Team names (config)
        team_republic            = "Republic",
        team_cis                 = "Separatists",

        -- Supply / pod names (config)
        supply_ammo              = "Ammo Crate",
        supply_repair            = "Repair",
        supply_airrefill         = "Air Resupply",
        supply_laat_atte         = "LAAT/C with AT-TE",
        pod_escapepod            = "Escape Pod",

        -- Misc
        no_team                  = "No team",
    },

    -- ── Spanish ──────────────────────────────
    es = {
        log_mysql_connected      = "Conexión MySQL establecida",
        log_mysql_table_error    = "Error creando tabla MySQL: ",
        log_mysql_fail           = "Fallo MySQL: ",
        log_mysql_load_error     = "Error cargando whitelist MySQL: ",
        log_mysql_save_row_error = "Error guardando fila MySQL: ",
        log_mysql_clear_error    = "Error limpiando whitelist MySQL: ",
        log_mysqloo_missing      = "mysqloo no está instalado, usando almacenamiento nativo",

        err_entity_not_found     = "No existe la entidad: ",
        err_cannot_create_ent    = "No se pudo crear la entidad ",
        err_hyperspace_missing   = "La entidad vanilla_hyperspace_ship no existe",
        err_hyperspace_anim_fail = "No se pudo crear la animación de hyperspace",
        err_capital_invalid      = "Nave capital inválida",
        err_capital_limit        = "Límite alcanzado para esa nave",
        err_capital_noent        = "No existe la entidad: ",
        err_capital_spawn_fail   = "Error al crear la nave capital: ",
        err_fighter_invalid      = "Caza inválido",
        err_fighter_limit        = "Límite alcanzado para ese caza",
        err_fighter_noent        = "No existe la entidad: ",
        err_fighter_no_capital   = "Tenés que seleccionar una nave capital de tu equipo",
        err_fighter_spawn_fail   = "No se pudo crear el caza",
        err_supply_invalid       = "Suministro inválido",
        err_supply_limit         = "Límite alcanzado para ese suministro",
        err_supply_noent         = "No existe la entidad: ",
        err_supply_no_capital    = "Tenés que seleccionar una nave capital de tu equipo",
        err_supply_no_target     = "Tenés que marcar un punto de entrega",
        err_supply_transport_missing = "No existe la entidad de transporte: ",
        err_supply_transport_fail    = "No se pudo crear el transporte de suministro",
        err_supply_spawn_fail    = "No se pudo crear el suministro",
        err_pod_invalid          = "Pod de escape inválido",
        err_pod_limit            = "Límite alcanzado para ese pod de escape",
        err_pod_noent            = "No existe la entidad: ",
        err_pod_no_capital       = "Tenés que seleccionar una nave capital de tu equipo",
        err_pod_no_target        = "Tenés que marcar un punto de caída",
        err_pod_no_players       = "Seleccioná al menos un jugador para el pod de escape",
        err_pod_spawn_fail       = "No se pudo crear el pod de escape",
        err_ship_invalid         = "Nave inválida",
        err_ship_not_registered  = "La nave no está registrada",
        err_turbolaser_missing   = "La entidad heart_turbolaser_spawner no existe",
        err_bombard_generic      = "No se pudo iniciar el bombardeo",

        chat_job_disabled        = "[GRN Navy] Tu trabajo no está habilitado para usar /navy",
        chat_no_whitelist_access = "[GRN Navy] No tenés acceso a la whitelist",
        chat_whitelist_saved     = "[GRN Navy] Whitelist actualizada",
        chat_capital_jumping     = "[GRN Navy] Nave capital entrando desde hyperspace",
        chat_fighter_deployed    = "[GRN Navy] Caza desplegado. Jugadores asignados: ",
        chat_supply_deployed     = "[GRN Navy] Suministro desplegado",
        chat_pod_deployed        = "[GRN Navy] Pod de escape desplegado. Jugadores asignados: ",
        chat_ship_withdrawn_fx   = "[GRN Navy] Nave retirada vía hyperspace",
        chat_ship_withdrawn_nofx = "[GRN Navy] Nave retirada (sin animación): ",
        chat_bombard_started     = "[GRN Navy] Bombardeo turboláser iniciado",
        chat_bombard_too_far     = "[GRN Navy] La nave está demasiado lejos para bombardear esa zona",
        chat_bombard_error       = "[GRN Navy] ",
        chat_welcome             = "[GRN Navy] Usá /navy si tu job fue habilitado y /whitelistnavy si sos staff autorizado",

        hud_controls             = "WASD mover cámara | Q/E rotar | Click izq seleccionar | rueda zoom | salir modo: ",
        hud_marking_supply       = " | MARCANDO SUMINISTRO",
        hud_marking_pod          = " | MARCANDO POD DE ESCAPE",
        hud_bombard_mode         = " | MODO BOMBARDERO",
        hud_move_mode            = " | MODO MOVER",
        hud_crosshair_target     = "Objetivo",
        hud_mode_supply          = "MARCAR SUMINISTRO",
        hud_mode_pod             = "MARCAR POD DE ESCAPE",
        hud_mode_bombard         = "MODO BOMBARDERO",
        hud_mode_move            = "MODO MOVER",
        hud_exit_hint            = " | presioná  para salir",

        menu_title               = "GRN Navy System",
        menu_loading             = "Cargando...",
        menu_team_prefix         = "Equipo: ",
        menu_no_team             = "Sin equipo",
        menu_available_players   = "Jugadores disponibles",
        menu_capital_ships       = "Naves Capitales",
        menu_btn_deploy_capital  = "Desplegar Capital",
        menu_btn_withdraw        = "Retirar Seleccionada",
        menu_fighters            = "Cazas",
        menu_fighters_hint       = "Seleccioná jugadores de la lista y luego desplegá el caza.",
        menu_btn_deploy_fighter  = "Desplegar Caza",
        menu_supplies            = "Suministros",
        menu_supplies_hint       = "Seleccioná la capital y luego marcá el punto donde debe llegar la nave de suministro.",
        menu_btn_request_supply  = "Solicitar Suministro y Marcar Punto",
        menu_escape_pods         = "Pods de Escape",
        menu_pods_hint           = "Pod LVS configurable. Seleccioná hasta 5 jugadores y luego marcá el punto de caída.",
        menu_btn_launch_pod      = "Lanzar Pod de Escape",
        menu_combat_control      = "Control de Combate",
        menu_btn_bombard         = "Modo Bombardero",
        menu_btn_move            = "Mover Nave",
        menu_btn_refresh         = "Actualizar",
        menu_btn_exit_mode       = "Salir del Modo Activo",
        menu_combat_hint         = "Seleccioná una nave, tocá Mover o Bombardeo y el menú se ocultará. La tecla configurada en config.lua también sale del modo.",
        menu_active_ships        = "Naves Activas",
        menu_ship_hp             = "HP",
        menu_ship_shield         = "Escudo",
        menu_btn_close           = "Cerrar / Salir del RTS",

        wl_title                 = "GRN Navy  ·  Whitelist",
        wl_col_job               = "Trabajo / Comando",
        wl_col_team              = "Equipo",
        wl_col_enabled           = "Habilitado",
        wl_team_republic         = "República",
        wl_team_cis              = "Separatistas",
        wl_btn_save              = "Guardar",

        team_republic            = "República",
        team_cis                 = "Separatistas",

        supply_ammo              = "Caja de munición",
        supply_repair            = "Reparación",
        supply_airrefill         = "Reabastecimiento aéreo",
        supply_laat_atte         = "LAAT/C con AT-TE",
        pod_escapepod            = "Pod de escape",
        no_team                  = "Sin equipo",
    },

    -- ── Portuguese ───────────────────────────
    pt = {
        log_mysql_connected      = "Conexão MySQL estabelecida",
        log_mysql_table_error    = "Erro ao criar tabela MySQL: ",
        log_mysql_fail           = "Falha MySQL: ",
        log_mysql_load_error     = "Erro ao carregar whitelist MySQL: ",
        log_mysql_save_row_error = "Erro ao salvar linha MySQL: ",
        log_mysql_clear_error    = "Erro ao limpar whitelist MySQL: ",
        log_mysqloo_missing      = "mysqloo não está instalado, usando armazenamento nativo",

        err_entity_not_found     = "Entidade não existe: ",
        err_cannot_create_ent    = "Não foi possível criar a entidade ",
        err_hyperspace_missing   = "A entidade vanilla_hyperspace_ship não existe",
        err_hyperspace_anim_fail = "Não foi possível criar animação de hyperspace",
        err_capital_invalid      = "Nave capital inválida",
        err_capital_limit        = "Limite atingido para essa nave",
        err_capital_noent        = "Entidade não existe: ",
        err_capital_spawn_fail   = "Erro ao criar nave capital: ",
        err_fighter_invalid      = "Caça inválido",
        err_fighter_limit        = "Limite atingido para esse caça",
        err_fighter_noent        = "Entidade não existe: ",
        err_fighter_no_capital   = "Você precisa selecionar uma nave capital da sua equipe",
        err_fighter_spawn_fail   = "Não foi possível criar o caça",
        err_supply_invalid       = "Suprimento inválido",
        err_supply_limit         = "Limite atingido para esse suprimento",
        err_supply_noent         = "Entidade não existe: ",
        err_supply_no_capital    = "Você precisa selecionar uma nave capital da sua equipe",
        err_supply_no_target     = "Você precisa marcar um ponto de entrega",
        err_supply_transport_missing = "Entidade de transporte não existe: ",
        err_supply_transport_fail    = "Não foi possível criar transporte de suprimento",
        err_supply_spawn_fail    = "Não foi possível criar o suprimento",
        err_pod_invalid          = "Cápsula de fuga inválida",
        err_pod_limit            = "Limite atingido para essa cápsula",
        err_pod_noent            = "Entidade não existe: ",
        err_pod_no_capital       = "Você precisa selecionar uma nave capital da sua equipe",
        err_pod_no_target        = "Você precisa marcar um ponto de queda",
        err_pod_no_players       = "Selecione pelo menos um jogador para a cápsula de fuga",
        err_pod_spawn_fail       = "Não foi possível criar a cápsula de fuga",
        err_ship_invalid         = "Nave inválida",
        err_ship_not_registered  = "Nave não está registrada",
        err_turbolaser_missing   = "A entidade heart_turbolaser_spawner não existe",
        err_bombard_generic      = "Não foi possível iniciar o bombardeio",

        chat_job_disabled        = "[GRN Navy] Seu trabalho não está habilitado para usar /navy",
        chat_no_whitelist_access = "[GRN Navy] Você não tem acesso à whitelist",
        chat_whitelist_saved     = "[GRN Navy] Whitelist atualizada",
        chat_capital_jumping     = "[GRN Navy] Nave capital entrando via hyperspace",
        chat_fighter_deployed    = "[GRN Navy] Caça implantado. Jogadores atribuídos: ",
        chat_supply_deployed     = "[GRN Navy] Suprimento implantado",
        chat_pod_deployed        = "[GRN Navy] Cápsula de fuga implantada. Jogadores atribuídos: ",
        chat_ship_withdrawn_fx   = "[GRN Navy] Nave retirada via hyperspace",
        chat_ship_withdrawn_nofx = "[GRN Navy] Nave retirada (sem animação): ",
        chat_bombard_started     = "[GRN Navy] Bombardeio turbolaser iniciado",
        chat_bombard_too_far     = "[GRN Navy] A nave está longe demais para bombardear essa área",
        chat_bombard_error       = "[GRN Navy] ",
        chat_welcome             = "[GRN Navy] Use /navy se seu trabalho foi habilitado e /whitelistnavy se você é staff autorizado",

        hud_controls             = "WASD mover câmera | Q/E girar | Clique esq selecionar | roda zoom | sair modo: ",
        hud_marking_supply       = " | MARCANDO SUPRIMENTO",
        hud_marking_pod          = " | MARCANDO CÁPSULA DE FUGA",
        hud_bombard_mode         = " | MODO BOMBARDEIO",
        hud_move_mode            = " | MODO MOVER",
        hud_crosshair_target     = "Alvo",
        hud_mode_supply          = "MARCAR SUPRIMENTO",
        hud_mode_pod             = "MARCAR CÁPSULA DE FUGA",
        hud_mode_bombard         = "MODO BOMBARDEIO",
        hud_mode_move            = "MODO MOVER",
        hud_exit_hint            = " | pressione  para sair",

        menu_title               = "GRN Navy System",
        menu_loading             = "Carregando...",
        menu_team_prefix         = "Equipe: ",
        menu_no_team             = "Sem equipe",
        menu_available_players   = "Jogadores disponíveis",
        menu_capital_ships       = "Naves Capitais",
        menu_btn_deploy_capital  = "Implantar Capital",
        menu_btn_withdraw        = "Retirar Selecionada",
        menu_fighters            = "Caças",
        menu_fighters_hint       = "Selecione jogadores da lista e depois implante o caça.",
        menu_btn_deploy_fighter  = "Implantar Caça",
        menu_supplies            = "Suprimentos",
        menu_supplies_hint       = "Selecione a capital e marque o ponto onde a nave de suprimento deve chegar.",
        menu_btn_request_supply  = "Solicitar Suprimento e Marcar Ponto",
        menu_escape_pods         = "Cápsulas de Fuga",
        menu_pods_hint           = "Pod LVS configurável. Selecione até 5 jogadores e marque o ponto de queda.",
        menu_btn_launch_pod      = "Lançar Cápsula de Fuga",
        menu_combat_control      = "Controle de Combate",
        menu_btn_bombard         = "Modo Bombardeio",
        menu_btn_move            = "Mover Nave",
        menu_btn_refresh         = "Atualizar",
        menu_btn_exit_mode       = "Sair do Modo Ativo",
        menu_combat_hint         = "Selecione uma nave, toque em Mover ou Bombardeio e o menu será ocultado. A tecla configurada em config.lua também sai do modo.",
        menu_active_ships        = "Naves Ativas",
        menu_ship_hp             = "HP",
        menu_ship_shield         = "Escudo",
        menu_btn_close           = "Fechar / Sair do RTS",

        wl_title                 = "GRN Navy  ·  Whitelist",
        wl_col_job               = "Trabalho / Comando",
        wl_col_team              = "Equipe",
        wl_col_enabled           = "Habilitado",
        wl_team_republic         = "República",
        wl_team_cis              = "Separatistas",
        wl_btn_save              = "Salvar",

        team_republic            = "República",
        team_cis                 = "Separatistas",

        supply_ammo              = "Caixa de munição",
        supply_repair            = "Reparo",
        supply_airrefill         = "Reabastecimento aéreo",
        supply_laat_atte         = "LAAT/C com AT-TE",
        pod_escapepod            = "Cápsula de fuga",
        no_team                  = "Sem equipe",
    },

    -- ── French ───────────────────────────────
    fr = {
        log_mysql_connected      = "Connexion MySQL établie",
        log_mysql_table_error    = "Erreur lors de la création de la table MySQL : ",
        log_mysql_fail           = "Échec MySQL : ",
        log_mysql_load_error     = "Erreur lors du chargement de la whitelist MySQL : ",
        log_mysql_save_row_error = "Erreur lors de la sauvegarde d'une ligne MySQL : ",
        log_mysql_clear_error    = "Erreur lors de la suppression de la whitelist MySQL : ",
        log_mysqloo_missing      = "mysqloo n'est pas installé, utilisation du stockage natif",

        err_entity_not_found     = "L'entité n'existe pas : ",
        err_cannot_create_ent    = "Impossible de créer l'entité ",
        err_hyperspace_missing   = "L'entité vanilla_hyperspace_ship n'existe pas",
        err_hyperspace_anim_fail = "Impossible de créer l'animation hyperspace",
        err_capital_invalid      = "Vaisseau capital invalide",
        err_capital_limit        = "Limite atteinte pour ce vaisseau",
        err_capital_noent        = "L'entité n'existe pas : ",
        err_capital_spawn_fail   = "Erreur lors de la création du vaisseau capital : ",
        err_fighter_invalid      = "Chasseur invalide",
        err_fighter_limit        = "Limite atteinte pour ce chasseur",
        err_fighter_noent        = "L'entité n'existe pas : ",
        err_fighter_no_capital   = "Vous devez sélectionner un vaisseau capital de votre équipe",
        err_fighter_spawn_fail   = "Impossible de créer le chasseur",
        err_supply_invalid       = "Ravitaillement invalide",
        err_supply_limit         = "Limite atteinte pour ce ravitaillement",
        err_supply_noent         = "L'entité n'existe pas : ",
        err_supply_no_capital    = "Vous devez sélectionner un vaisseau capital de votre équipe",
        err_supply_no_target     = "Vous devez marquer un point de livraison",
        err_supply_transport_missing = "L'entité de transport n'existe pas : ",
        err_supply_transport_fail    = "Impossible de créer le transport de ravitaillement",
        err_supply_spawn_fail    = "Impossible de créer le ravitaillement",
        err_pod_invalid          = "Capsule de sauvetage invalide",
        err_pod_limit            = "Limite atteinte pour cette capsule",
        err_pod_noent            = "L'entité n'existe pas : ",
        err_pod_no_capital       = "Vous devez sélectionner un vaisseau capital de votre équipe",
        err_pod_no_target        = "Vous devez marquer un point de chute",
        err_pod_no_players       = "Sélectionnez au moins un joueur pour la capsule de sauvetage",
        err_pod_spawn_fail       = "Impossible de créer la capsule de sauvetage",
        err_ship_invalid         = "Vaisseau invalide",
        err_ship_not_registered  = "Le vaisseau n'est pas enregistré",
        err_turbolaser_missing   = "L'entité heart_turbolaser_spawner n'existe pas",
        err_bombard_generic      = "Impossible de démarrer le bombardement",

        chat_job_disabled        = "[GRN Navy] Votre métier n'est pas activé pour utiliser /navy",
        chat_no_whitelist_access = "[GRN Navy] Vous n'avez pas accès à la whitelist",
        chat_whitelist_saved     = "[GRN Navy] Whitelist mise à jour",
        chat_capital_jumping     = "[GRN Navy] Vaisseau capital entrant par hyperespace",
        chat_fighter_deployed    = "[GRN Navy] Chasseur déployé. Joueurs assignés : ",
        chat_supply_deployed     = "[GRN Navy] Ravitaillement déployé",
        chat_pod_deployed        = "[GRN Navy] Capsule de sauvetage déployée. Joueurs assignés : ",
        chat_ship_withdrawn_fx   = "[GRN Navy] Vaisseau retiré via hyperespace",
        chat_ship_withdrawn_nofx = "[GRN Navy] Vaisseau retiré (sans animation) : ",
        chat_bombard_started     = "[GRN Navy] Bombardement turbolaser lancé",
        chat_bombard_too_far     = "[GRN Navy] Le vaisseau est trop loin pour bombarder cette zone",
        chat_bombard_error       = "[GRN Navy] ",
        chat_welcome             = "[GRN Navy] Utilisez /navy si votre emploi a été activé et /whitelistnavy si vous êtes staff autorisé",

        hud_controls             = "WASD déplacer caméra | Q/E pivoter | Clic gauche sélectionner | molette zoom | quitter mode : ",
        hud_marking_supply       = " | MARQUAGE RAVITAILLEMENT",
        hud_marking_pod          = " | MARQUAGE CAPSULE DE SAUVETAGE",
        hud_bombard_mode         = " | MODE BOMBARDEMENT",
        hud_move_mode            = " | MODE DÉPLACEMENT",
        hud_crosshair_target     = "Cible",
        hud_mode_supply          = "MARQUER RAVITAILLEMENT",
        hud_mode_pod             = "MARQUER CAPSULE DE SAUVETAGE",
        hud_mode_bombard         = "MODE BOMBARDEMENT",
        hud_mode_move            = "MODE DÉPLACEMENT",
        hud_exit_hint            = " | appuyez sur  pour quitter",

        menu_title               = "GRN Navy System",
        menu_loading             = "Chargement...",
        menu_team_prefix         = "Équipe : ",
        menu_no_team             = "Aucune équipe",
        menu_available_players   = "Joueurs disponibles",
        menu_capital_ships       = "Vaisseaux Capitaux",
        menu_btn_deploy_capital  = "Déployer Capital",
        menu_btn_withdraw        = "Retirer Sélectionné",
        menu_fighters            = "Chasseurs",
        menu_fighters_hint       = "Sélectionnez des joueurs dans la liste, puis déployez le chasseur.",
        menu_btn_deploy_fighter  = "Déployer Chasseur",
        menu_supplies            = "Ravitaillements",
        menu_supplies_hint       = "Sélectionnez le capital puis marquez le point où le vaisseau de ravitaillement doit arriver.",
        menu_btn_request_supply  = "Demander Ravitaillement & Marquer Point",
        menu_escape_pods         = "Capsules de Sauvetage",
        menu_pods_hint           = "Pod LVS configurable. Sélectionnez jusqu'à 5 joueurs et marquez le point de chute.",
        menu_btn_launch_pod      = "Lancer Capsule de Sauvetage",
        menu_combat_control      = "Contrôle de Combat",
        menu_btn_bombard         = "Mode Bombardement",
        menu_btn_move            = "Déplacer Vaisseau",
        menu_btn_refresh         = "Actualiser",
        menu_btn_exit_mode       = "Quitter le Mode Actif",
        menu_combat_hint         = "Sélectionnez un vaisseau, appuyez sur Déplacer ou Bombardement et le menu se masquera. La touche configurée dans config.lua quitte aussi le mode.",
        menu_active_ships        = "Vaisseaux Actifs",
        menu_ship_hp             = "PV",
        menu_ship_shield         = "Bouclier",
        menu_btn_close           = "Fermer / Quitter RTS",

        wl_title                 = "GRN Navy  ·  Whitelist",
        wl_col_job               = "Emploi / Commande",
        wl_col_team              = "Équipe",
        wl_col_enabled           = "Activé",
        wl_team_republic         = "République",
        wl_team_cis              = "Séparatistes",
        wl_btn_save              = "Sauvegarder",

        team_republic            = "République",
        team_cis                 = "Séparatistes",

        supply_ammo              = "Caisse de munitions",
        supply_repair            = "Réparation",
        supply_airrefill         = "Ravitaillement aérien",
        supply_laat_atte         = "LAAT/C avec AT-TE",
        pod_escapepod            = "Capsule de sauvetage",
        no_team                  = "Aucune équipe",
    },

    -- ── German ───────────────────────────────
    de = {
        log_mysql_connected      = "MySQL-Verbindung hergestellt",
        log_mysql_table_error    = "Fehler beim Erstellen der MySQL-Tabelle: ",
        log_mysql_fail           = "MySQL-Fehler: ",
        log_mysql_load_error     = "Fehler beim Laden der MySQL-Whitelist: ",
        log_mysql_save_row_error = "Fehler beim Speichern der MySQL-Zeile: ",
        log_mysql_clear_error    = "Fehler beim Löschen der MySQL-Whitelist: ",
        log_mysqloo_missing      = "mysqloo ist nicht installiert, nativer Speicher wird verwendet",

        err_entity_not_found     = "Entität existiert nicht: ",
        err_cannot_create_ent    = "Entität konnte nicht erstellt werden ",
        err_hyperspace_missing   = "Die Entität vanilla_hyperspace_ship existiert nicht",
        err_hyperspace_anim_fail = "Hyperspace-Animation konnte nicht erstellt werden",
        err_capital_invalid      = "Ungültiges Kapitalschiff",
        err_capital_limit        = "Limit für dieses Schiff erreicht",
        err_capital_noent        = "Entität existiert nicht: ",
        err_capital_spawn_fail   = "Fehler beim Erstellen des Kapitalschiffs: ",
        err_fighter_invalid      = "Ungültiger Jäger",
        err_fighter_limit        = "Limit für diesen Jäger erreicht",
        err_fighter_noent        = "Entität existiert nicht: ",
        err_fighter_no_capital   = "Sie müssen ein Kapitalschiff Ihres Teams auswählen",
        err_fighter_spawn_fail   = "Jäger konnte nicht erstellt werden",
        err_supply_invalid       = "Ungültige Versorgung",
        err_supply_limit         = "Limit für diese Versorgung erreicht",
        err_supply_noent         = "Entität existiert nicht: ",
        err_supply_no_capital    = "Sie müssen ein Kapitalschiff Ihres Teams auswählen",
        err_supply_no_target     = "Sie müssen einen Lieferpunkt markieren",
        err_supply_transport_missing = "Transport-Entität existiert nicht: ",
        err_supply_transport_fail    = "Versorgungstransport konnte nicht erstellt werden",
        err_supply_spawn_fail    = "Versorgung konnte nicht erstellt werden",
        err_pod_invalid          = "Ungültige Rettungskapsel",
        err_pod_limit            = "Limit für diese Kapsel erreicht",
        err_pod_noent            = "Entität existiert nicht: ",
        err_pod_no_capital       = "Sie müssen ein Kapitalschiff Ihres Teams auswählen",
        err_pod_no_target        = "Sie müssen einen Abwurfpunkt markieren",
        err_pod_no_players       = "Wählen Sie mindestens einen Spieler für die Rettungskapsel",
        err_pod_spawn_fail       = "Rettungskapsel konnte nicht erstellt werden",
        err_ship_invalid         = "Ungültiges Schiff",
        err_ship_not_registered  = "Schiff ist nicht registriert",
        err_turbolaser_missing   = "Die Entität heart_turbolaser_spawner existiert nicht",
        err_bombard_generic      = "Bombardierung konnte nicht gestartet werden",

        chat_job_disabled        = "[GRN Navy] Ihr Job ist nicht für /navy aktiviert",
        chat_no_whitelist_access = "[GRN Navy] Sie haben keinen Zugriff auf die Whitelist",
        chat_whitelist_saved     = "[GRN Navy] Whitelist aktualisiert",
        chat_capital_jumping     = "[GRN Navy] Kapitalschiff tritt per Hyperraum ein",
        chat_fighter_deployed    = "[GRN Navy] Jäger eingesetzt. Zugewiesene Spieler: ",
        chat_supply_deployed     = "[GRN Navy] Versorgung eingesetzt",
        chat_pod_deployed        = "[GRN Navy] Rettungskapsel eingesetzt. Zugewiesene Spieler: ",
        chat_ship_withdrawn_fx   = "[GRN Navy] Schiff per Hyperraum zurückgezogen",
        chat_ship_withdrawn_nofx = "[GRN Navy] Schiff zurückgezogen (keine Animation): ",
        chat_bombard_started     = "[GRN Navy] Turbolaser-Bombardierung gestartet",
        chat_bombard_too_far     = "[GRN Navy] Das Schiff ist zu weit entfernt, um diesen Bereich zu bombardieren",
        chat_bombard_error       = "[GRN Navy] ",
        chat_welcome             = "[GRN Navy] Verwenden Sie /navy, wenn Ihr Job aktiviert wurde, und /whitelistnavy, wenn Sie autorisiertes Personal sind",

        hud_controls             = "WASD Kamera bewegen | Q/E drehen | Linksklick auswählen | Rad zoomen | Modus verlassen: ",
        hud_marking_supply       = " | VERSORGUNG MARKIEREN",
        hud_marking_pod          = " | RETTUNGSKAPSEL MARKIEREN",
        hud_bombard_mode         = " | BOMBARDIERUNGSMODUS",
        hud_move_mode            = " | BEWEGUNGSMODUS",
        hud_crosshair_target     = "Ziel",
        hud_mode_supply          = "VERSORGUNG MARKIEREN",
        hud_mode_pod             = "RETTUNGSKAPSEL MARKIEREN",
        hud_mode_bombard         = "BOMBARDIERUNGSMODUS",
        hud_mode_move            = "BEWEGUNGSMODUS",
        hud_exit_hint            = " | drücken Sie  zum Verlassen",

        menu_title               = "GRN Navy System",
        menu_loading             = "Wird geladen...",
        menu_team_prefix         = "Team: ",
        menu_no_team             = "Kein Team",
        menu_available_players   = "Verfügbare Spieler",
        menu_capital_ships       = "Kapitalschiffe",
        menu_btn_deploy_capital  = "Kapital einsetzen",
        menu_btn_withdraw        = "Ausgewähltes zurückziehen",
        menu_fighters            = "Jäger",
        menu_fighters_hint       = "Wählen Sie Spieler aus der Liste und setzen Sie dann den Jäger ein.",
        menu_btn_deploy_fighter  = "Jäger einsetzen",
        menu_supplies            = "Versorgung",
        menu_supplies_hint       = "Wählen Sie das Kapital aus und markieren Sie dann den Punkt, wo das Versorgungsschiff ankommen soll.",
        menu_btn_request_supply  = "Versorgung anfordern & Punkt markieren",
        menu_escape_pods         = "Rettungskapseln",
        menu_pods_hint           = "Konfigurierbarer LVS-Pod. Wählen Sie bis zu 5 Spieler und markieren Sie den Abwurfpunkt.",
        menu_btn_launch_pod      = "Rettungskapsel starten",
        menu_combat_control      = "Kampfsteuerung",
        menu_btn_bombard         = "Bombardierungsmodus",
        menu_btn_move            = "Schiff bewegen",
        menu_btn_refresh         = "Aktualisieren",
        menu_btn_exit_mode       = "Aktiven Modus verlassen",
        menu_combat_hint         = "Wählen Sie ein Schiff, tippen Sie auf Bewegen oder Bombardierung und das Menü wird ausgeblendet. Die in config.lua konfigurierte Taste beendet den Modus ebenfalls.",
        menu_active_ships        = "Aktive Schiffe",
        menu_ship_hp             = "HP",
        menu_ship_shield         = "Schild",
        menu_btn_close           = "Schließen / RTS verlassen",

        wl_title                 = "GRN Navy  ·  Whitelist",
        wl_col_job               = "Job / Befehl",
        wl_col_team              = "Team",
        wl_col_enabled           = "Aktiviert",
        wl_team_republic         = "Republik",
        wl_team_cis              = "Separatisten",
        wl_btn_save              = "Speichern",

        team_republic            = "Republik",
        team_cis                 = "Separatisten",

        supply_ammo              = "Munitionskiste",
        supply_repair            = "Reparatur",
        supply_airrefill         = "Luftversorgung",
        supply_laat_atte         = "LAAT/C mit AT-TE",
        pod_escapepod            = "Rettungskapsel",
        no_team                  = "Kein Team",
    },
}


function GRN_NAVY.T(key)
    local lang = (GRN_NAVY.Config and GRN_NAVY.Config.Language) or "en"
    local tbl  = L.Strings[lang] or L.Strings["en"]
    return tbl[key] or L.Strings["en"][key] or ("[?" .. tostring(key) .. "]")
end
