game.AddParticles( "particles/explosions_fx.pcf" )
game.AddParticles( "particles/astw2_halo_pack_weapon_projectiles.pcf" )
game.AddParticles( "particles/astw2_halo_pack_explosions.pcf" )
PrecacheParticleSystem("grenade_final")
PrecacheParticleSystem("explosion_grenade")
PrecacheParticleSystem("astw2_halo_ce_fuel_rod_trail")
PrecacheParticleSystem("astw2_halo_2_fuel_rod_explosion")

game.AddParticles("particles/doi_explosion_fx_grenade.pcf")
game.AddParticles("particles/doi_explosion_fx_new.pcf")

PrecacheParticleSystem("explosion_he_grenade")
PrecacheParticleSystem("water_explosion")
PrecacheParticleSystem("explosion_m79")
PrecacheParticleSystem("explosion_m79_body")
PrecacheParticleSystem("explosion_he_m79")
PrecacheParticleSystem("explosion_mortarb")
PrecacheParticleSystem("claymore_dustwave")
PrecacheParticleSystem("claymore_fastsmoke")
PrecacheParticleSystem("claymore_shockwave")
PrecacheParticleSystem("claymore_smoke")
PrecacheParticleSystem("claymore_smoke_b")
PrecacheParticleSystem("m79_shrapnel")
PrecacheParticleSystem("m79_smoke_e")
PrecacheParticleSystem("m79_trails_c")
PrecacheParticleSystem("m79_shockwave")
PrecacheParticleSystem("m79_flash")
PrecacheParticleSystem("smoke_plume")
PrecacheParticleSystem("explosion_lensflare")

local particlefiles = {
	"mw2019_effects.pcf",
	"mw2019_tracer.pcf",
	"mw2019_rockettrail.pcf",
	"mw2019_explosions_pak.pcf",
}

for k, v in pairs(particlefiles) do
	game.AddParticles("particles/"..v)
end

local particlenames = {
    "mw2019_tracer",
    "mw2019_tracer_fast",
	"mw2019_tracer_slow",
	"mw2019_tracer_small",
	"mw2019_tracer_inc",
	"weapon_tracers_incendiary",
	"thermite_thrown_trail",
	"smoke_thrown_trail",
	"grenadetrail",
	"rockettrail",
	"smoketrail",
	"Generic_explo_emp",
	"Generic_explo_flash",
	"Generic_explo_vhigh",
	"Generic_explo_high",
	"Generic_explo_mid",
	"Generic_explo_tiny"
}

for k, v in pairs(particlenames) do
	PrecacheParticleSystem(v)
end

GSORParticleFiles = {}
table.insert(GSORParticleFiles, #GSORParticleFiles, "csgo_inferno_fx")
table.insert(GSORParticleFiles, #GSORParticleFiles, "arc9_gsr_nadefx")

GSORParticleEffects = {}
table.insert(GSORParticleEffects, #GSORParticleEffects, "bumpmine_active")
table.insert(GSORParticleEffects, #GSORParticleEffects, "bumpmine_active_glow")
table.insert(GSORParticleEffects, #GSORParticleEffects, "bumpmine_active_glow2")
table.insert(GSORParticleEffects, #GSORParticleEffects, "bumpmine_active_glow_outer")
table.insert(GSORParticleEffects, #GSORParticleEffects, "bumpmine_detonate")
table.insert(GSORParticleEffects, #GSORParticleEffects, "bumpmine_player_trail")
table.insert(GSORParticleEffects, #GSORParticleEffects, "grenade_explosion_01")
table.insert(GSORParticleEffects, #GSORParticleEffects, "weapon_sensorgren_beeplight")
table.insert(GSORParticleEffects, #GSORParticleEffects, "weapon_sensorgren_detonate")
table.insert(GSORParticleEffects, #GSORParticleEffects, "weapon_molotov_thrown")
//EXPLOSION_FX
table.insert(GSORParticleEffects, #GSORParticleEffects, "c4_timer_light")
table.insert(GSORParticleEffects, #GSORParticleEffects, "c4_timer_light_trigger")
table.insert(GSORParticleEffects, #GSORParticleEffects, "c4_timer_light_held")
table.insert(GSORParticleEffects, #GSORParticleEffects, "c4_timer_light_dropped")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_c4_500")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_coop_mission_c4")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_basic")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_hegrenade_interior")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_hegrenade_brief")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_smoke_disperse")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_smokegrenade")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_smokegrenade_fallback")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_smokegrenade_CT")
table.insert(GSORParticleEffects, #GSORParticleEffects, "HE_shockwave")
//INFERNO FX
table.insert(GSORParticleEffects, #GSORParticleEffects, "molotov_explosion")
table.insert(GSORParticleEffects, #GSORParticleEffects, "molotov_fire01")
table.insert(GSORParticleEffects, #GSORParticleEffects, "molotov_groundfire")
table.insert(GSORParticleEffects, #GSORParticleEffects, "molotov_fire_main_gm")
table.insert(GSORParticleEffects, #GSORParticleEffects, "molotov_fire_child_gm")
table.insert(GSORParticleEffects, #GSORParticleEffects, "molotov_groundfire_00HIGH")
table.insert(GSORParticleEffects, #GSORParticleEffects, "molotov_groundfire_00MEDIUM")
table.insert(GSORParticleEffects, #GSORParticleEffects, "extinguish_fire")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_molotov_air")
table.insert(GSORParticleEffects, #GSORParticleEffects, "incgrenade_thrown_trail")
table.insert(GSORParticleEffects, #GSORParticleEffects, "weapon_molotov_held")
//SMOKE FX
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_child_smoke03e")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_child_core06b")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_child_smoke07b")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_child_smoke07c")
table.insert(GSORParticleEffects, #GSORParticleEffects, "explosion_child_distort01c")

for k, v in pairs(GSORParticleFiles) do
	game.AddParticles("particles/" .. v .. ".pcf")
end

for k, v in pairs(GSORParticleEffects) do
end

game.AddParticles( "particles/csgo_weapon_fx.pcf" )
game.AddParticles( "particles/csgo_explosions_fx.pcf" )

PrecacheParticleSystem("pb_ins2_muzzleflash_tracer")
PrecacheParticleSystem("weapon_muzzle_flash_attach_comp")
PrecacheParticleSystem("weapon_muzzle_flash_assaultrifle")
PrecacheParticleSystem("weapon_muzzle_flash_assaultrifle_comp")
PrecacheParticleSystem("weapon_muzzle_flash_assaultrifle_silenced")
PrecacheParticleSystem("weapon_muzzle_flash_assaultrifle_silenced2")
PrecacheParticleSystem("weapon_muzzle_flash_shotgun_parent_silenced")
PrecacheParticleSystem("weapon_muzzle_flash_awp")
PrecacheParticleSystem("weapon_muzzle_flash_autoshotgun")
PrecacheParticleSystem("weapon_muzzle_flash_huntingrifle")
PrecacheParticleSystem("weapon_muzzle_flash_huntingrifle_FP")
PrecacheParticleSystem("weapon_muzzle_flash_magnum")
PrecacheParticleSystem("weapon_muzzle_flash_pistol")
PrecacheParticleSystem("weapon_muzzle_flash_pistol_silenced")
PrecacheParticleSystem("weapon_muzzle_flash_pistol_elite")
PrecacheParticleSystem("weapon_muzzle_flash_shotgun")
PrecacheParticleSystem("weapon_muzzle_flash_shotgun2")
PrecacheParticleSystem("weapon_muzzle_flash_smg")
PrecacheParticleSystem("weapon_muzzle_flash_para")
PrecacheParticleSystem("weapon_muzzle_flash_para_FP")
PrecacheParticleSystem("weapon_muzzle_flash_taser")
PrecacheParticleSystem("weapon_muzzle_flash_HE")
PrecacheParticleSystem("weapon_shell_casing_50cal")
PrecacheParticleSystem("weapon_shell_casing_9mm")
PrecacheParticleSystem("weapon_shell_casing_9mm_FP")
PrecacheParticleSystem("weapon_shell_casing_rifle")
PrecacheParticleSystem("weapon_shell_casing_shotgun")
PrecacheParticleSystem("weapon_shell_casing_50cal_fallback")
PrecacheParticleSystem("weapon_shell_casing_9mm_fallback")
PrecacheParticleSystem("weapon_shell_casing_rifle_fallback")
PrecacheParticleSystem("weapon_shell_casing_shotgun_fallback")
PrecacheParticleSystem("weapon_muzzle_smoke")
PrecacheParticleSystem("weapon_muzzle_smoke_long")
PrecacheParticleSystem("weapon_muzzle_smoke_pistols")
PrecacheParticleSystem("muzzle_smoke_trace")
PrecacheParticleSystem("weapon_muzzle_flash_smoke_small")
PrecacheParticleSystem("weapon_muzzle_flash_smoke_small2")
PrecacheParticleSystem("weapon_muzzle_flash_smoke_small3")
PrecacheParticleSystem("weapon_muzzle_flash_smoke_small4")
PrecacheParticleSystem("weapon_muzzle_flash_smoke_medium")
PrecacheParticleSystem("weapon_sensorgren_beeplight")
PrecacheParticleSystem("weapon_sensorgren_detonate")
PrecacheParticleSystem("weapon_tracers")
PrecacheParticleSystem("weapon_tracers_50cal")
PrecacheParticleSystem("weapon_tracers_mach")
PrecacheParticleSystem("weapon_tracers_pistol")
PrecacheParticleSystem("weapon_tracers_taser")

PrecacheParticleSystem("explosion_basic")
PrecacheParticleSystem("explosion_hegrenade_brief")
PrecacheParticleSystem("explosion_hegrenade_interior")
PrecacheParticleSystem("explosion_basic_water")
PrecacheParticleSystem("explosion_c4_500")
PrecacheParticleSystem("explosion_c4_500_fallback")
PrecacheParticleSystem("explosion_smokegrenade")
PrecacheParticleSystem("explosion_child_smoke03e")
PrecacheParticleSystem("explosion_child_core06b")
PrecacheParticleSystem("explosion_child_smoke07b")
PrecacheParticleSystem("explosion_child_smoke07c")
PrecacheParticleSystem("explosion_child_distort01c")

PrecacheParticleSystem("muzzle_weapon_smoke_v2_direction")
PrecacheParticleSystem("muzzle_weapon_smoke_v2")

-- Dioxis gas particles (from arc9_gsr_nadefx.pcf)
PrecacheParticleSystem("AC_nade_gas_dust")
PrecacheParticleSystem("AC_nade_gas_explode")
PrecacheParticleSystem("AC_nade_gas_ejection")


game.AddParticles( "particles/bloomtest.pcf" )
game.AddParticles( "particles/boxglove_fx.pcf" )
game.AddParticles( "particles/corrosion_fx.pcf" )
game.AddParticles( "particles/cryo_fx.pcf" )
game.AddParticles( "particles/darkling_fx.pcf" )
game.AddParticles( "particles/fallingstar_fx.pcf" )
game.AddParticles( "particles/gravrifle_fx.pcf" )
game.AddParticles( "particles/hellfire_fx.pcf" )
game.AddParticles( "particles/hwave_fx.pcf" )
game.AddParticles( "particles/lanka_fx.pcf" )
game.AddParticles( "particles/ngen_fx.pcf" )
game.AddParticles( "particles/nio_fx.pcf" )
game.AddParticles( "particles/pulsar_fx.pcf" )
game.AddParticles( "particles/spectra_fx.pcf" )
game.AddParticles( "particles/stinger_fx.pcf" )
game.AddParticles( "particles/storm_fx.pcf" )
game.AddParticles( "particles/tbolt_fx_reborn.pcf" )
game.AddParticles( "particles/trace_fx.pcf" )
game.AddParticles( "particles/umbra_fx.pcf" )
game.AddParticles( "particles/underscore_fx.pcf" )
game.AddParticles( "particles/vapor_fx.pcf" )
game.AddParticles( "particles/veho_fx.pcf" )

PrecacheParticleSystem( "_ghost_upgrade" )
PrecacheParticleSystem( "_wraithgun_muzzle" )
PrecacheParticleSystem( "_wraithgun_tracer" )
PrecacheParticleSystem( "_wraithgun_hit" )
PrecacheParticleSystem( "_wrath_hit_sparks" )
PrecacheParticleSystem( "_wrath_tracer" )
PrecacheParticleSystem( "aeblast_muzzle" )
PrecacheParticleSystem( "aquamarine_charge" )
PrecacheParticleSystem( "aquamarine_tracer" )
PrecacheParticleSystem( "asa6_hit" )
PrecacheParticleSystem( "asa6_tracer" )
PrecacheParticleSystem( "astra_beam" )
PrecacheParticleSystem( "astra_beam_lightning_1" )
PrecacheParticleSystem( "astra_bolt" )
PrecacheParticleSystem( "astra_hit" )
PrecacheParticleSystem( "astra_hit_heavy" )
PrecacheParticleSystem( "astra_muzzle" )
PrecacheParticleSystem( "astra_muzzle_heavy" )
PrecacheParticleSystem( "astra_muzzle_lightning" )
PrecacheParticleSystem( "blade_glow" )
PrecacheParticleSystem( "blade_hit" )
PrecacheParticleSystem( "bloom_beam_0" )
PrecacheParticleSystem( "bloom_halo_0" )
PrecacheParticleSystem( "celest_dissolve" )
PrecacheParticleSystem( "celest_wrath_core" )
PrecacheParticleSystem( "celest_wrath_core_charging" )
PrecacheParticleSystem( "celest_wrath_dissolve" )
PrecacheParticleSystem( "celest_wrath_explode" )
PrecacheParticleSystem( "celest_wrath_hit" )
PrecacheParticleSystem( "celest_wrath_muzzle" )
PrecacheParticleSystem( "celest_wrath_nade" )
PrecacheParticleSystem( "celest_wrath_pulse" )
PrecacheParticleSystem( "celest_wrath_tracer" )
PrecacheParticleSystem( "corro_muzzle" )
PrecacheParticleSystem( "corro_proc" )
PrecacheParticleSystem( "corro_tracer" )
PrecacheParticleSystem( "corruptor_impact" )
PrecacheParticleSystem( "corruptor_muzzle" )
PrecacheParticleSystem( "corruptor_tracer" )
PrecacheParticleSystem( "crsv_dissolve" )
PrecacheParticleSystem( "crsv_dissolve_cheap" )
PrecacheParticleSystem( "cryo_explosion_large" )
PrecacheParticleSystem( "cryo_ragshatter" )
PrecacheParticleSystem( "cryo_ragshatter_frags" )
PrecacheParticleSystem( "drake_hit" )
PrecacheParticleSystem( "drake_muzzle" )
PrecacheParticleSystem( "drake_tracer" )
PrecacheParticleSystem( "ember_hit_entity" )
PrecacheParticleSystem( "ember_hit_nothing" )
PrecacheParticleSystem( "ember_hit_world" )
PrecacheParticleSystem( "ember_laser" )
PrecacheParticleSystem( "ember_laser_underwater" )
PrecacheParticleSystem( "ember_muzzle" )
PrecacheParticleSystem( "ember_muzzle_turnoff" )
PrecacheParticleSystem( "ember_muzzle_turnon" )
PrecacheParticleSystem( "ember_underwater_bubbles" )
PrecacheParticleSystem( "emg_tracer" )
PrecacheParticleSystem( "emg_hit" )
PrecacheParticleSystem( "eml_dps_shock" )
PrecacheParticleSystem( "eml_generic_blast" )
PrecacheParticleSystem( "eml_generic_crsv" )
PrecacheParticleSystem( "eml_generic_crsv_splat" )
PrecacheParticleSystem( "eml_generic_cryo" )
PrecacheParticleSystem( "eml_generic_cryo_ground" )
PrecacheParticleSystem( "eml_generic_heat" )
PrecacheParticleSystem( "eml_generic_shock" )
PrecacheParticleSystem( "eml_generic_cryo_small" )
PrecacheParticleSystem( "eml_muzzle_cryo" )
PrecacheParticleSystem( "eml_tracer_cryo" )
PrecacheParticleSystem( "event_onwater_remove" )
PrecacheParticleSystem( "fathom_blast" )
PrecacheParticleSystem( "fathom_cloud" )
PrecacheParticleSystem( "fathom_death" )
PrecacheParticleSystem( "fathom_muzzle" )
PrecacheParticleSystem( "flare_halo_0" )
PrecacheParticleSystem( "flathr" )
PrecacheParticleSystem( "fstar_charge" )
PrecacheParticleSystem( "fstar_hit" )
PrecacheParticleSystem( "fstar_freeze_catch" )
PrecacheParticleSystem( "fstar_freeze_release" )
PrecacheParticleSystem( "fstar_muzzle" )
PrecacheParticleSystem( "fstar_muzzle_altfire" )
PrecacheParticleSystem( "fstar_tracer" )
PrecacheParticleSystem( "fstar_secfire" )
PrecacheParticleSystem( "fstar_sfire_hit_swave" )
PrecacheParticleSystem( "gravrifle_blast" )
PrecacheParticleSystem( "gravrifle_blast_parentable" )
PrecacheParticleSystem( "gravrifle_blast_smoke" )
PrecacheParticleSystem( "gravrifle_charge" )
PrecacheParticleSystem( "gravrifle_dissolve" )
PrecacheParticleSystem( "gravrifle_hit" )
PrecacheParticleSystem( "gravrifle_nade" )
PrecacheParticleSystem( "gravrifle_tracer" )
PrecacheParticleSystem( "grinder_muzzle" )
PrecacheParticleSystem( "gunsmoke" )
PrecacheParticleSystem( "hellfire_muzzle" )
PrecacheParticleSystem( "hellfire_muzzle_smoke" )
PrecacheParticleSystem( "hellfire_tracer" )
PrecacheParticleSystem( "hellfire_blast" )
PrecacheParticleSystem( "hellnade_fragments" )
PrecacheParticleSystem( "hellnade_heat" )
PrecacheParticleSystem( "hellnade_shockwave" )
PrecacheParticleSystem( "hornet_blast" )
PrecacheParticleSystem( "hornet_blast_charged" )
PrecacheParticleSystem( "hornet_blast_cheap" )
PrecacheParticleSystem( "hornet_trail" )
PrecacheParticleSystem( "hornet_trail_cheaper" )
PrecacheParticleSystem( "hwave_charge" )
PrecacheParticleSystem( "hwave_charged" )
PrecacheParticleSystem( "hwave_debris_small" )
PrecacheParticleSystem( "hwave_hit" )
PrecacheParticleSystem( "hwave_hit_fleks" )
PrecacheParticleSystem( "hwave_muzzle" )
PrecacheParticleSystem( "hwave_muzzle_embers" )
PrecacheParticleSystem( "hwave_muzzle_finish" )
PrecacheParticleSystem( "hwave_tracer" )
PrecacheParticleSystem( "hwave_tracer_cheap" )
PrecacheParticleSystem( "ice_crystals" )
PrecacheParticleSystem( "ice_crystals_2" )
PrecacheParticleSystem( "ice_crystals_3" )
PrecacheParticleSystem( "ice_freezing" )
PrecacheParticleSystem( "ice_freezing_shortlt" )
PrecacheParticleSystem( "ice_freezing_release" )
PrecacheParticleSystem( "ice_impact" )
PrecacheParticleSystem( "ice_impact_heavy" )
PrecacheParticleSystem( "ice_tracer_smoke" )
PrecacheParticleSystem( "ice_muzzle_small" )
PrecacheParticleSystem( "ice_sfire_charge" )
PrecacheParticleSystem( "item_flare" )
PrecacheParticleSystem( "item_orb_battery" )
PrecacheParticleSystem( "item_orb_health" )
PrecacheParticleSystem( "item_orb_upgrade" )
PrecacheParticleSystem( "item_pfx_battery" )
PrecacheParticleSystem( "item_pfx_health" )
PrecacheParticleSystem( "item_pfx_upgrade" )
PrecacheParticleSystem( "item_pkin_amb" )
PrecacheParticleSystem( "item_pkin_break" )
PrecacheParticleSystem( "item_upg_break" )
PrecacheParticleSystem( "jotunn_charge_init" )
PrecacheParticleSystem( "jotunn_charging" )
PrecacheParticleSystem( "jotunn_muzzle" )
PrecacheParticleSystem( "lanka_hit_riv" )
PrecacheParticleSystem( "lapis_vent" )
PrecacheParticleSystem( "meridian_tracer" )
PrecacheParticleSystem( "moby_hit" )
PrecacheParticleSystem( "moby_muzzle" )
PrecacheParticleSystem( "moby_tracer" )
PrecacheParticleSystem( "ngen_core_playerfx" )
PrecacheParticleSystem( "ngen_core_small" )
PrecacheParticleSystem( "ngen_core_small_cheap" )
PrecacheParticleSystem( "ngen_explosion" )
PrecacheParticleSystem( "ngen_explosion_energy" )
PrecacheParticleSystem( "ngen_hit" )
PrecacheParticleSystem( "ngen_hit_lgtning" )
PrecacheParticleSystem( "ngen_hit_sparks_2" )
PrecacheParticleSystem( "ngen_missile_smoke" )
PrecacheParticleSystem( "ngen_muzzle" )
PrecacheParticleSystem( "ngen_muzzle_2" )
PrecacheParticleSystem( "ngen_muzzle_3" )
PrecacheParticleSystem( "ngen_muzzle_4" )
PrecacheParticleSystem( "ngen_muzzle_4_shotgun" )
PrecacheParticleSystem( "ngen_muzzle_4_simplified" )
PrecacheParticleSystem( "ngen_muzzle_charge" )
PrecacheParticleSystem( "ngen_muzzle_embers_overheat" )
PrecacheParticleSystem( "ngen_tracer" )
PrecacheParticleSystem( "nio_beam" )
PrecacheParticleSystem( "nio_muzzle" )
PrecacheParticleSystem( "nio_impact" )
PrecacheParticleSystem( "nio_dissolve" )
PrecacheParticleSystem( "nio_dissolve_cheap" )
PrecacheParticleSystem( "nio_charge" )
PrecacheParticleSystem( "nrg_hit" )
PrecacheParticleSystem( "nrg_tracer" )
PrecacheParticleSystem( "onwater_bubbles" )
PrecacheParticleSystem( "panda_charge" )
PrecacheParticleSystem( "panda_charged" )
PrecacheParticleSystem( "panda_hit" )
PrecacheParticleSystem( "panda_muzzle" )
PrecacheParticleSystem( "panda_tracer" )
PrecacheParticleSystem( "pele_hit")
PrecacheParticleSystem( "pele_muzzle")
PrecacheParticleSystem( "pele_tracer")
PrecacheParticleSystem( "pest_muzzle" )
PrecacheParticleSystem( "pest_hit" )
PrecacheParticleSystem( "phasma_absorb" )
PrecacheParticleSystem( "phasma_blade_enable" )
PrecacheParticleSystem( "phasma_blade_enable_sparks" )
PrecacheParticleSystem( "phasma_blade_disable" )
PrecacheParticleSystem( "phasma_blade_sparks" )
PrecacheParticleSystem( "phasma_blast" )
PrecacheParticleSystem( "phasma_core" )
PrecacheParticleSystem( "phasma_initial_mist" )
PrecacheParticleSystem( "phasma_trail" )
PrecacheParticleSystem( "phasma_w_blade_enable" )
PrecacheParticleSystem( "phasma_w_initial_mist" )
PrecacheParticleSystem( "phasma_w_trail" )
PrecacheParticleSystem( "prisma_core" )
PrecacheParticleSystem( "pulsar_charge" )
PrecacheParticleSystem( "pulsar_charge_fail" )
PrecacheParticleSystem( "pulsar_beam" )
PrecacheParticleSystem( "pulsar_hit_weak" )
PrecacheParticleSystem( "pulsar_muzzle" )
PrecacheParticleSystem( "pyro_dissolve" )
PrecacheParticleSystem( "pyro_dissolve_ash_0" )
PrecacheParticleSystem( "pyro_dissolve_ash_3" )
PrecacheParticleSystem( "pyro_dissolve_cheap" )
PrecacheParticleSystem( "pyro_dissolve_ash_cheap" )
PrecacheParticleSystem( "pyro_explode" )
PrecacheParticleSystem( "pyro_nade" )
PrecacheParticleSystem( "saphyre_absorb" )
PrecacheParticleSystem( "saphyre_hit" )
PrecacheParticleSystem( "saphyre_hit_fleks" )
PrecacheParticleSystem( "saphyre_muzzle" )
PrecacheParticleSystem( "saphyre_muzzle_embers" )
PrecacheParticleSystem( "saphyre_muzzle_flames_0a" )
PrecacheParticleSystem( "saphyre_tracer" )
PrecacheParticleSystem( "sentinel_hit" )
PrecacheParticleSystem( "sentinel_muzzle" )
PrecacheParticleSystem( "seraph_hit" )
PrecacheParticleSystem( "seraph_muzzle" )
PrecacheParticleSystem( "seraph_tracer" )
PrecacheParticleSystem( "shk_hit" )
PrecacheParticleSystem( "shk_muzzle" )
PrecacheParticleSystem( "shk_tracer" )
PrecacheParticleSystem( "spectra_blast" )
PrecacheParticleSystem( "spectra_charging" )
PrecacheParticleSystem( "spectra_core" )
PrecacheParticleSystem( "spectra_core_crsv" )
PrecacheParticleSystem( "spectra_core_evensmaller" )
PrecacheParticleSystem( "spectra_core_fire" )
PrecacheParticleSystem( "spectra_core_ice" )
PrecacheParticleSystem( "spectra_core_small" )
PrecacheParticleSystem( "spectra_explode" )
PrecacheParticleSystem( "spectra_fmchange" )
PrecacheParticleSystem( "spectra_hit" )
PrecacheParticleSystem( "spectra_muzzle" )
PrecacheParticleSystem( "spectra_muzzle_2" )
PrecacheParticleSystem( "spectra_muzzle_old" )
PrecacheParticleSystem( "spectra_muzzle_overheat" )
PrecacheParticleSystem( "spectra_tracer" )
PrecacheParticleSystem( "spr_explosion" )
PrecacheParticleSystem( "spr_explosion_large" )
PrecacheParticleSystem( "spr_explosion_large_flash_noz" )
PrecacheParticleSystem( "spr_explosion_large_smoshroom" )
PrecacheParticleSystem( "spr_hit" )
PrecacheParticleSystem( "spr_muzzle" )
PrecacheParticleSystem( "spr_nade_tick" )
PrecacheParticleSystem( "spr_tracer" )
PrecacheParticleSystem( "stinger_muzzle" )
PrecacheParticleSystem( "stinger_core_small" )
PrecacheParticleSystem( "stinger_explode" )
PrecacheParticleSystem( "stinger_muzzle_2" )
PrecacheParticleSystem( "stinger_core_small_2" )
PrecacheParticleSystem( "stinger_explode_2" )
PrecacheParticleSystem( "supra_c_hit" )
PrecacheParticleSystem( "supra_charging" )
PrecacheParticleSystem( "supra_mirv" )
PrecacheParticleSystem( "supra_nade" )
PrecacheParticleSystem( "supra_p_hit" )
PrecacheParticleSystem( "storm_muzzle" )
PrecacheParticleSystem( "storm_muzzle_cheap" )
PrecacheParticleSystem( "tbolt_muzzle" )
PrecacheParticleSystem( "tbolt_hit" )
PrecacheParticleSystem( "tbolt_tracer" )
PrecacheParticleSystem( "tbolt_tracer_cheap" )
PrecacheParticleSystem( "trace_muzzle" )
PrecacheParticleSystem( "trace_trace" )
PrecacheParticleSystem( "trace_projectile" )
PrecacheParticleSystem( "trace_projectile_pws" )
PrecacheParticleSystem( "trace_sparks_new" )
PrecacheParticleSystem( "umbra_ammo" )
PrecacheParticleSystem( "umbra_ammo_pickup" )
PrecacheParticleSystem( "umbra_ammo_consumed" )
PrecacheParticleSystem( "umbra_cast" )
PrecacheParticleSystem( "umbra_core" )
PrecacheParticleSystem( "umbra_darken" )
PrecacheParticleSystem( "umbra_darken_stackup" )
PrecacheParticleSystem( "umbra_hit" )
PrecacheParticleSystem( "umbra_muzzle" )
PrecacheParticleSystem( "umbra_muzzle_embers" )
PrecacheParticleSystem( "umbra_muzzle_vented" )
PrecacheParticleSystem( "umbra_ptru" )
PrecacheParticleSystem( "umbra_shutdown_flecks" )
PrecacheParticleSystem( "umbra_succumb" )
PrecacheParticleSystem( "vapor" )
PrecacheParticleSystem( "vapor_cheap" )
PrecacheParticleSystem( "vapor_charge_glow" )
PrecacheParticleSystem( "vapor_charge_secfire" )
PrecacheParticleSystem( "vapor_collapse" )
PrecacheParticleSystem( "vapor_collapse_cheap" )
PrecacheParticleSystem( "vapor_muzzle" )
PrecacheParticleSystem( "vapor_muzzle_altfire" )
PrecacheParticleSystem( "vapor_muzzle_evensmaller" )
PrecacheParticleSystem( "vapor_muzzle_small" )
PrecacheParticleSystem( "vectra_charged" )
PrecacheParticleSystem( "vectra_charging" )
PrecacheParticleSystem( "vp_binary_muzzle" )
PrecacheParticleSystem( "vp_binary_tracer" )
PrecacheParticleSystem( "vp_dissolve" )
PrecacheParticleSystem( "vp_dissolve_cheap" )
PrecacheParticleSystem( "vsecfire_shockwave" )
PrecacheParticleSystem( "vh_muzzle" )
PrecacheParticleSystem( "vh_tracer_old" )
PrecacheParticleSystem( "vh_hit" )
PrecacheParticleSystem( "xplo_tracer" )
PrecacheParticleSystem( "xplo_hit" )
PrecacheParticleSystem( "xplo_hit_cheap" )
PrecacheParticleSystem( "zeala_charged" )
PrecacheParticleSystem( "zeala_charging" )
PrecacheParticleSystem( "zeala_burst" )
PrecacheParticleSystem( "zeala_muzzle" )
PrecacheParticleSystem( "zeala_nade" )
PrecacheParticleSystem( "zeala_vortex" )
PrecacheParticleSystem( "zeala_vortex_cheap" )

game.AddParticles("particles/muzzleflash_dragonsbreath.pcf")
PrecacheParticleSystem("muzzleflash_dragonbreath")
game.AddParticles("particles/uo_explosions_fas2.pcf")
PrecacheParticleSystem("explosion_HE_m79_fas2")
PrecacheParticleSystem("explosion_he_grenade_fas2")
PrecacheParticleSystem("explosion_HE_claymore_fas2")
PrecacheParticleSystem("explosion_grenade_fas2")

game.AddParticles( "particles/swbf/astw2_swbf_explosions.pcf" )
game.AddParticles( "particles/swbf/astw2_star_wars_battlefront_muzzle_effects.pcf" )
game.AddParticles( "particles/swbf/astw2_swbf_flamethrower.pcf" )
game.AddParticles( "particles/swbf/astw2_swbf_rocket_fx.pcf" )
game.AddParticles( "particles/swbf/astw2_swbf_impact_fx.pcf" )
game.AddParticles( "particles/swbf/astw2_swbf_pickup_effects.pcf" )
game.AddParticles( "particles/swbf/astw2_swbf_tracer.pcf" )
game.AddParticles( "particles/swbf/swbf_commandpost_fx.pcf" )

PrecacheParticleSystem( "astw2_swbf_explosion_cis_launcher" )
PrecacheParticleSystem( "astw2_swbf_explosion_cis_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_cis_wristrocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_concussion_grenade" )
PrecacheParticleSystem( "astw2_swbf_explosion_emp" )
PrecacheParticleSystem( "astw2_swbf_explosion_imp_launcher" )
PrecacheParticleSystem( "astw2_swbf_explosion_imp_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_reb_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_rep_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_thermal_detonator" )
PrecacheParticleSystem( "astw2_swbf_explosion_thermal_detonator2" )
PrecacheParticleSystem( "astw2_swbf_explosion_rep_emp_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_death_droid" )

PrecacheParticleSystem( "astw2_swbf_muzzle_tor_rifle" )
PrecacheParticleSystem( "astw2_swbf_muzzle_sth_rifle" )
PrecacheParticleSystem( "astw2_swbf_muzzle_cis_blaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_cis_pistol" )
PrecacheParticleSystem( "astw2_swbf_muzzle_cis_sniper" )
PrecacheParticleSystem( "astw2_swbf_muzzle_cis_bulldog" )
PrecacheParticleSystem( "astw2_swbf_muzzle_imp_blaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_imp_pistol" )
PrecacheParticleSystem( "astw2_swbf_muzzle_imp_shotgun" )
PrecacheParticleSystem( "astw2_swbf_muzzle_imp_sniper" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_blaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_pistol" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_sniper" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_shotgun" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_bowcaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_rep_blaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_rep_pistol" )
PrecacheParticleSystem( "astw2_swbf_muzzle_rep_sniper" )
PrecacheParticleSystem( "astw2_swbf_muzzle_tus_rifle" )

PrecacheParticleSystem( "astw2_swbf_rocket_fx_generic" )
PrecacheParticleSystem( "astw2_swbf_rocket_fx_all" )
PrecacheParticleSystem( "astw2_swbf_rocket_fx_cis" )
PrecacheParticleSystem( "astw2_swbf_rocket_fx_imp" )
PrecacheParticleSystem( "astw2_swbf_rocket_fx_rep" )

PrecacheParticleSystem( "astw2_swbf_blaster_bolt_impact" )
PrecacheParticleSystem( "astw2_swbf_blaster_bolt_impact_yellow" )
PrecacheParticleSystem( "astw2_swbf_blaster_bolt_impact_heavy" )

PrecacheParticleSystem( "astw2_swbf_flamethrower_fx" )
PrecacheParticleSystem( "astw2_swbf_pickup_ammo" )
PrecacheParticleSystem( "astw2_swbf_pickup_bacta" )
PrecacheParticleSystem( "astw2_swbf_pickup_dual" )
PrecacheParticleSystem( "astw2_swbf_pickup_energy" )
PrecacheParticleSystem( "astw2_swbf_pickup_rage" )
PrecacheParticleSystem( "astw2_swbf_pickup_rally" )

PrecacheParticleSystem( "swbf_command_post_ally" )
PrecacheParticleSystem( "swbf_command_post_friendly" )
PrecacheParticleSystem( "swbf_command_post_enemy" )
PrecacheParticleSystem( "swbf_command_post_neutral" )
PrecacheParticleSystem( "swbf_command_post_unoccupied" )

PrecacheParticleSystem( "astw2_swbf_tracer_arc_caster" )
PrecacheParticleSystem( "astw2_swbf_tracer_blaster_blue" )
PrecacheParticleSystem( "astw2_swbf_tracer_blaster_green" )
PrecacheParticleSystem( "astw2_swbf_tracer_blaster_orange" )
PrecacheParticleSystem( "astw2_swbf_tracer_blaster_purple" )
PrecacheParticleSystem( "astw2_swbf_tracer_blaster_red" )
PrecacheParticleSystem( "astw2_swbf_tracer_blaster_yellow" )
PrecacheParticleSystem( "astw2_swbf_tracer_sniper_blue" )
PrecacheParticleSystem( "astw2_swbf_tracer_sniper_crimson" )
PrecacheParticleSystem( "astw2_swbf_tracer_sniper_green" )
PrecacheParticleSystem( "astw2_swbf_tracer_sniper_red" )
PrecacheParticleSystem( "astw2_swbf_tracer_sniper_yellow" )
PrecacheParticleSystem( "astw2_swbf_tracer_sniper_teal" )
game.AddParticles( "particles/BlasterOrange.pcf" )
game.AddParticles( "particles/BlasterBlue.pcf" )
game.AddParticles( "particles/BlasterGreen.pcf" )
game.AddParticles( "particles/BlasterPurple.pcf" )
game.AddParticles( "particles/BlasterRed.pcf" )
game.AddParticles( "particles/BlasterYellow.pcf" )

game.AddParticles( "particles/pulsar_fx_red.pcf" )
game.AddParticles( "particles/shitsonfireyo.pcf" )

PrecacheParticleSystem( "shitsonfireyo" )
PrecacheParticleSystem( "pulsar_beam_red" )
PrecacheParticleSystem("wpn_muzzleflash_mgl_FULL")
PrecacheParticleSystem("tfa_apex_tracer_anvil")
PrecacheParticleSystem("tfa_apex_tracer_ar")
PrecacheParticleSystem("tfa_apex_tracer_hmg")
PrecacheParticleSystem("tfa_apex_tracer_hmg_rampage")
PrecacheParticleSystem("tfa_apex_tracer_pistol")
PrecacheParticleSystem("tfa_apex_tracer_shotgun")
PrecacheParticleSystem("tfa_apex_tracer_smg")
PrecacheParticleSystem("tfa_apex_tracer_sniper")
PrecacheParticleSystem("tfa_apex_lstar_explode_core")
PrecacheParticleSystem("tfa_apex_arcstar_explode")
PrecacheParticleSystem("tfa_apex_frag_explode")
PrecacheParticleSystem("tfa_apex_arcstar_impact")
PrecacheParticleSystem("tfa_apex_bocek_impact")
PrecacheParticleSystem("tfa_apex_bocek_trail")
PrecacheParticleSystem("tfa_apex_bullet_trail")
PrecacheParticleSystem("tfa_apex_bullet_energy_trail")
PrecacheParticleSystem("tfa_apex_bullet_sent_trail")

PrecacheParticleSystem("tfa_apex_energy_muzzle_big") 
PrecacheParticleSystem("tfa_apex_energy_muzzle_medium")
PrecacheParticleSystem("tfa_apex_energy_muzzle_havoc")
PrecacheParticleSystem("tfa_apex_energy_muzzle_ttake")
PrecacheParticleSystem("tfa_apex_energy_muzzle_shotgun")
PrecacheParticleSystem("tfa_apex_energy_muzzle_lstar")
PrecacheParticleSystem("tfa_apex_chargerifle_muzzle")
PrecacheParticleSystem("tfa_apex_chargerifle_muzzle_charge")

PrecacheParticleSystem( "blaster_muzzle_orange" )
PrecacheParticleSystem( "blaster_muzzle_blue" )
PrecacheParticleSystem( "blaster_muzzle_red" )
PrecacheParticleSystem( "blaster_muzzle_green" )
PrecacheParticleSystem( "blaster_muzzle_purple" )

PrecacheParticleSystem( "wpn_muzzleflash_dc17_red" )
PrecacheParticleSystem( "wpn_muzzleflash_dc17_purple" )
PrecacheParticleSystem( "wpn_muzzleflash_dc17_green" )
PrecacheParticleSystem( "wpn_muzzleflash_dc17_orange" )
PrecacheParticleSystem( "wpn_muzzleflash_dc17" )
PrecacheParticleSystem( "muzzleflash_smg" )
PrecacheParticleSystem( "muzzleflash_smg_bizon" )
PrecacheParticleSystem( "muzzleflash_shotgun" )
PrecacheParticleSystem( "muzzleflash_slug" )
PrecacheParticleSystem( "muzzleflash_slug_flame" )
PrecacheParticleSystem( "muzzleflash_pistol" )
PrecacheParticleSystem( "muzzleflash_pistol_cleric" )
PrecacheParticleSystem( "muzzleflash_pistol_deagle" )
PrecacheParticleSystem( "muzzleflash_suppressed" )
PrecacheParticleSystem( "muzzleflash_mp5" )
PrecacheParticleSystem( "muzzleflash_MINIMI" )
PrecacheParticleSystem( "muzzleflash_m79" )
PrecacheParticleSystem( "muzzleflash_m14" )
PrecacheParticleSystem( "muzzleflash_ak47" )
PrecacheParticleSystem( "muzzleflash_ak74" )
PrecacheParticleSystem( "muzzleflash_m82" )
PrecacheParticleSystem( "muzzleflash_m3" )
PrecacheParticleSystem( "muzzleflash_famas" )
PrecacheParticleSystem( "muzzleflash_g3" )
PrecacheParticleSystem( "muzzleflash_1" )
PrecacheParticleSystem( "muzzleflash_3" )
PrecacheParticleSystem( "muzzleflash_4" )
PrecacheParticleSystem( "muzzleflash_5" )
PrecacheParticleSystem( "muzzleflash_6" )
